const ROLE_ADMIN = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
};

const LEVEL = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  ADVANCED: "ADVANCED",
  EXPERT: "EXPERT",
};

const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
};

const ROLE = {
  USER_BASIC: "USER_BASIC",
  USER_PREMIUM: "USER_PREMIUM",
  VENDOR: "VENDOR",
};

module.exports = { ROLE_ADMIN, LEVEL, STATUS, ROLE };
