const LEVEL = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  ADVANCED: "ADVANCED",
  EXPERT: "EXPERT",
};

const STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
};

const ROLE = {
  USER_BASIC: "USER_BASIC",
  USER_PREMIUM: "USER_PREMIUM",
  VENDOR: "VENDOR",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
};

const CALORIES_BURN = {
  WALKING: 0.53,
  JOGGING: 0.62,
  RUNNING: 0.75,
  OTHER: 0.68,
};

module.exports = { LEVEL, STATUS, ROLE, CALORIES_BURN };
